# -*- coding: utf-8 -*-
"""first 2 max elemrnts in list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtSbjSxh12O7q3GYKSa3otKGyjYVPlKx
"""

#Write a python code to find first two maximum no in a list.

mylist=[]
n=int(input())
for i in range (0,n):
    x=int(input())
    mylist.append(x)
sorted(mylist)
y=max(mylist)
print(max(mylist))
mylist.remove(max(mylist))
print(max(mylist))
mylist.append(y)

def maxele2(arr,n):
  max1=arr[0]
  max2=arr[0]
  for i in range (0,n):
    if arr[i]>max1:
      max2=max1
      max1=arr[i]
    else :
      max2=max(max2,arr[i])
  print("first maximum number =",max1)
  print("second maximum number=",max2)

list1=[]
n=int(input())
for i in range (0,n):
  x=int(input())
  list1.append(x)
maxele2(list1,n)