# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F60id9SpEUui9zPlr67wW2MeahuYpeyY
"""

'''Extract id numbers in a list from below, can use in built python functions, but donot use Loop:

{"orders":[{"id":1},{"id":2},{"id":3},{"id":4},{"id":5},{"id":6},{"id":7},{"id":8},{"id":9},{"id":10}
,{"id":11},{"id":648},{"id":649},{"id":650},{"id":651},{"id":652},{"id":653}],"errors":[{"code":3,"message":"[PHP Warning #2] 
count(): Parameter must be an array or an object that implements Countable (153)"}]}
'''

import re

data = '{"orders":[{"id":1},{"id":2},{"id":3},{"id":4},{"id":5},{"id":6},{"id":7},{"id":8},{"id":9},{"id":10},'\
        '{"id":11},{"id":648},{"id":649},{"id":650},{"id":651},{"id":652},{"id":653}],'\
        '"errors":[{"code":3,"message":"[PHP Warning #2] count(): Parameter must be an array or an object that implements Countable (153)"}]}'

numbers = re.findall(r'"id":(\d+)', data)
numbers = [int(x) for x in numbers]

print(numbers)