# -*- coding: utf-8 -*-
"""interchange first and last elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VI2LAY1u-usTXNa9ttt-vxKx6TsSyWPD
"""

#Write a python script to interchange first and last element of given list.

list=[]
n=int(input())
for i in range (0,n):
    x=int(input())
    list.append(x)

size=len(list)
temp=list[0]
list[0]=list[n-1]
list[n-1]=temp

print(list)